#!/usr/bin/env bash

if ! command -v clang-format &> /dev/null
then
    echo "clang_format could not be found"
    exit
fi

UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

for FILE in $(git diff --cached --name-only $UPSTREAM_BRANCH | grep -E 'resources/.*\.(js|mjs)')
do
echo $FILE
clang-format -i $FILE
done

if [[ $(git diff --stat) != '' ]]; then
  echo "Some JS files were auto-formatted, please re-commit:"
  git diff --stat
fi
