#!/usr/bin/env bash

if ! command -v clang-format &> /dev/null
then
    echo "clang_format could not be found"
    exit
fi

UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

for FILE in $(git diff --cached --name-only $UPSTREAM_BRANCH | grep -E 'resources/runner/.*\.(js|mjs)')
do
clang-format -i $FILE
done

exit 1
