name: todomvc
description: A TodoMVC app created using the Jaspr Dart web framework.
version: 0.1.0

environment:
    sdk: ^3.7.0

dependencies:
    jaspr: ^0.19.1

dev_dependencies:
    build_runner:
    build_web_compilers: ^4.1.0
    jaspr_builder:
    jaspr_lints:
    jaspr_cli:
    lints:

jaspr:
    mode: client
