export default [
    {
        rules: {
            "array-bracket-spacing": [2, "never"],
            "block-spacing": [2, "always"],
            "brace-style": 2,
            "comma-dangle": [2, "only-multiline"],
            "comma-spacing": [2, { before: false, after: true }],
            "comma-style": [2, "last"],
            "consistent-return": 2,
            curly: ["error", "multi-or-nest", "consistent"],
            "dot-notation": 0,
            "eol-last": 2,
            eqeqeq: 2,
            indent: ["error", 4, { SwitchCase: 1 }],
            "func-call-spacing": [2, "never"],
            "key-spacing": [2, { beforeColon: false, afterColon: true }],
            "keyword-spacing": [2, { before: true, after: true }],
            "new-cap": 0,
            "new-parens": 0,
            "no-console": 0,
            "no-constant-condition": 0,
            "no-extra-bind": 2,
            "no-extra-parens": [2, "all", { nestedBinaryExpressions: false }],
            "no-extra-semi": 2,
            "no-global-assign": 2,
            "no-inner-declarations": 0,
            "no-multi-spaces": 2,
            "no-multiple-empty-lines": ["error", { max: 1 }],
            "no-new": 0,
            "no-proto": 0,
            "no-redeclare": 0,
            "no-return-assign": 2,
            "no-return-await": 2,
            "no-self-compare": 2,
            "no-shadow": 0,
            "no-trailing-spaces": 2,
            "no-undef": 2,
            "no-underscore-dangle": 0,
            "no-unused-expressions": 2,
            "no-unused-vars": [2, { vars: "all", args: "none" }],
            "no-use-before-define": 0,
            "nonblock-statement-body-position": ["error", "below"],
            "object-curly-spacing": ["error", "always"],
            "operator-linebreak": ["error", "before"],
            "prefer-template": 2,
            quotes: [2, "double", { avoidEscape: true }],
            semi: 2,
            "semi-spacing": [2, { before: false, after: true }],
            "space-infix-ops": 2,
            "spaced-comment": [2, "always"],
            strict: 0,
            "valid-typeof": 2,
        },
        languageOptions: {
            globals: {
                browser: true,
                node: true,
                worker: true,
                es2022: true,
                // new globals
                customElements: true,
                CSSStyleSheet: true,
                ResizeObserver: true,
                CustomEvent: true,
                Event: true,
            },
            parserOptions: {
                sourceType: "module",
            },
        },
        ignores: ["dist/**/*", "src/tailwind.generated.css", "src/tailwind.chat-window.generated.css"],
    },
];
