name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  cache: "npm"

            - name: Install Node Packages
              run: npm ci

            - name: Build Workloads
              run: npm run build
