import { MAX_VISIBLE_TREE_VIEW_ITEM_DEPTH } from "../../params";
import { generateTreeHead } from "./../tree-generator";

import ChevronRight from "./../assets/Smock_ChevronRight_18_N.svg";
import TaskListIcon from "./../assets/Smock_TaskList_18_N.svg";

const FolderWrapper = (props) => {
    const { treeNode, currentDepth } = props;

    const children = [];
    treeNode.children.forEach((child) => {
        children.push(<TreeItem treeNode={child} currentDepth={currentDepth + 1} />);
    });

    return <ul className="spectrum-TreeView spectrum-TreeView--sizeS">{children}</ul>;
};

const TreeItem = (props) => {
    const { treeNode, currentDepth } = props;

    const isExpandableItem = treeNode.type === "expandableItem";
    // We always push the first child of treeNode because we know that treeNode.children.length is 1 if the item is expandable
    const children = isExpandableItem ? <FolderWrapper treeNode={treeNode.children[0]} currentDepth={currentDepth + 1} /> : null;
    const treeViewItemIsOpen = isExpandableItem && currentDepth < MAX_VISIBLE_TREE_VIEW_ITEM_DEPTH ? "is-open" : "";
    return (
        <li className={`spectrum-TreeView-item ${treeViewItemIsOpen}`}>
            <a className="spectrum-TreeView-itemLink">
                {treeNode.type === "nonExpandableItem"
                    ? <TaskListIcon className="task-list-icon spectrum-Icon spectrum-TreeView-itemIndicator spectrum-TreeView-itemIcon spectrum-Icon--sizeM" />
                    : <ChevronRight className="spectrum-Icon spectrum-TreeView-itemIndicator spectrum-TreeView-itemIcon" />
                }

                <span className="just-span spectrum-TreeView-itemLabel">{isExpandableItem ? "Sprint" : "Todo List"}</span>
            </a>
            {children}
        </li>
    );
};

/**
 * FolderWrapper generates 1 dom element.
 * TreeItem generates either 5 or 10 elements because ChevronRight is
 * inlined as a svg element with one path child and TaskListIcon is
 * inlined as a svg element with 4 path children and one defs child.
 *
 * To reach 1 element, the following dom structure is generated (list):
 * <ul></ul>
 *
 * To reach 5 elements, the following dom structure is generated (expandableItem, chevronRight):
 * <li class="spectrum-TreeView-item is-open">
 *  <a class="spectrum-TreeView-itemLink">
 *      <svg>
 *          <path></path>
 *      </svg>
 *      <span>Sprint</span>
 *  </a>
 *  <ul></ul> // Not counted here because it's generated by FolderWrapper
 * </li>
 * To reach 10 elements, the following dom structure is generated (nonExpandableItem, TaskListIcon):
 * <li class="spectrum-TreeView-item">
 *   <a class="spectrum-TreeView-itemLink">
 *     <svg>
 *       <defs><style>.Smock_TaskList_18_N_svg__fill{fill:#464646}</style></defs>
 *       <path></path>
 *       <path></path>
 *       <rect></rect>
 *       <rect></rect>
 *     </svg>
 *     <span>Todo List</span>
 *   </a>
 * </li>
 */
export const TreeArea = () => {
    const treeOptions = { listWeight: 1, expandableItemWeight: 5, nonExpandableItemWeight: 10 };
    const treeHead = generateTreeHead(treeOptions);
    return (
        <div className="tree-area">
            <h4 className="spectrum-Heading spectrum-Heading--sizeXS">Sprints</h4>
            <FolderWrapper treeNode={treeHead} currentDepth={0} />
        </div>
    );
};
